### ISSUE TITLE
Не создается науч.рук на сайте http://vkr.comp-gluk.ru/

### ISSUE THREAD

**Issue by tak1803** [rozh1/FinalWork#9]
Здравствуйте. 
Для указания рецензента необходимо сначала добавить темы своей ВКР и научного руководителя. В выпадающем списке моего науч.рука нет. При создании новой карточки: заполнила все данные, нажимаю кнопку добавить. После чего страница выходит на предыдущую (где выпадающий список), но новой записи моей там не появляется. Обновление станицы и выход/вход из учетной записи не помогли.
При повторном создании науч.рук данные введенные в полях сохраняются (т.е. при наведении на поле можно выбрать их).
Татьяна, группа 4291.

**Comment by rozh1** [comment]
Проблема с добавлением научных руководителей решена.
